import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import DashboardLayoutWrapper from "./DashboardLayoutWrapper";
import { GoogleTagManagerNoscript } from "@/components/GoogleTagManager/GoogleTagManagerNoscript";
import GoogleTagManager from "@/components/GoogleTagManager/GoogleTagManager";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AllMart-Avenue",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <GoogleTagManager />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased`}
      >

        <DashboardLayoutWrapper>
          <GoogleTagManagerNoscript />

          {children}</DashboardLayoutWrapper>
      </body>
    </html>
  );
}
